repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
          - id: end-of-file-fixer
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
          - id: trailing-whitespace
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
          - id: requirements-txt-fixer
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
          - id: mixed-line-ending
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v2.0.1
      hooks:
          - id: hadolint-system
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other)
            args:
                - "--ignore"
                - "DL3003"
                - "--ignore"
                - "DL3006"
                - "--ignore"
                - "DL3010"
                - "--ignore"
                - "DL3008"
                - "--ignore"
                - "DL4001"
                - "--ignore"
                - "DL3007"
    - repo: https://github.com/codespell-project/codespell.git
      rev: "v2.1.0" # Use the sha / tag you want to point at
      hooks:
          - id: codespell
            types: [text]
            exclude: ^(rootfs/webapp/static/css/other/|rootfs/webapp/static/js/other/|.+\.json|Logo-Sources|acarshub-typescript/css/other/|acarshub-typescript/js-other|rootfs/webapp/adsb.py|acarshub-typescript/src/interfaces.ts)
