version: '3.8'

services:
  sdrplay-beast1090:
    image: ghcr.io/sdr-enthusiasts/docker-sdrplay-beast1090
    tty: true
    container_name: sdrplay-beast1090
    hostname: sdrplay-beast1090
    restart: always
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - /dev/shm:/dev/shm:rw
    tmpfs:
      - /run:exec,size=256M
      - /tmp:size=128M
      - /var/log:size=32M
    environment:
      - I_AGREE_TO_THE_SDRPLAY_LICENSE=false
      - DUMP1090_EXTRA_ARGS=--fix --max-range 500 --phase-enhance --lat xx.xxxxx --lon yy.yyyyy --adsbMode 1
