#!/bin/bash

#shellcheck disable=SC1091
source /scripts/common

SCRIPT_NAME="$(basename "$0")"
SCRIPT_NAME="${SCRIPT_NAME%.*}"

ARCH=$(uname -m)

# if we're on an unsupported architecture SDR play isn't installed, exit
if [ "${ARCH}" != "aarch64" ] && [ "$ARCH" != "x86_64" ]; then
    exit 0
fi

# see if the user has sdrplay in the $SOAPYSDR $SOAPYSDRDRIVER text

if [ -z "$SOAPYSDR" ] && [ -z "$SOAPYSDRDRIVER" ]; then
    exit 0
fi

# if the user has sdrplay in the $SOAPYSDR $SOAPYSDRDRIVER text

if [[ "$SOAPYSDR" != *"sdrplay"* ]] && [[ "$SOAPYSDRDRIVER" != *"sdrplay"* ]]; then
    exit 0
fi

# verify we have the license file

if [ ! -f /sdrplay_license.txt ]; then
    echo "No license file found. Exiting..."
    exit 0
fi

# shellcheck disable=SC2034
s6wrap=(s6wrap --quiet --timestamps --prepend="$SCRIPT_NAME" --args)

#shellcheck disable=SC2154
"${s6wrap[@]}" echo "-------------------------------------------------------------------------------------------------------------------------------------"
"${s6wrap[@]}" echo "IMPORTANT - READ THE FOLLOWING - IMPORTANT - READ THE FOLLOWING - IMPORTANT - READ THE FOLLOWING"
"${s6wrap[@]}" echo ""
"${s6wrap[@]}" echo "This container uses SDRPlay API V3. YOU MAY ONLY USE THIS CONTAINER IN AGREEMENT WITH THE LICENSE FOR SDRPlay API V3."
"${s6wrap[@]}" echo ""
"${s6wrap[@]}" cat /sdrplay_license.txt
"${s6wrap[@]}" echo ""
"${s6wrap[@]}" echo "If you want to reread the terms of this license, please execute the following command:"
"${s6wrap[@]}" echo "docker exec -it <container name> cat /sdrplay_license.txt"
"${s6wrap[@]}" echo "If you do not agree with the terms of this license for any reason, please STOP and REMOVE this container immediately!"
"${s6wrap[@]}" echo "-------------------------------------------------------------------------------------------------------------------------------------"

