#!/command/with-contenv bash
#shellcheck shell=bash

#shellcheck disable=SC1091
source /scripts/common

# avoid fast loops when dump1090 fails and allow drivers to be established 
sleep 5

s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

# shellcheck disable=SC2086
"${s6wrap[@]}" /usr/bin/dump1090 --quiet --dev-sdrplay ${DUMP1090_EXTRA_ARGS}
